# This sets the default config for each job to use full VMs.
# The VMs have 2 cores and 8 GB of RAM
dist: trusty
sudo: required
services:
  - mysql
language: python
python:
  - "3.6"
cache: pip

before_install:
  - sh script/install/before_install.sh
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - sh script/install/install.sh

script:
  - conda init bash
  - source ~/.bashrc
  - conda activate eva
  - sh script/test/test.sh

after_success:
  - coveralls
